CREATE DATABASE chat_bd;

USE chat_bd;

CREATE TABLE messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    content VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


SHOW VARIABLES LIKE 'event_scheduler';
