-- MySQL Script generated by MySQL Workbench
-- Wed Jun 28 16:31:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema control_access
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `control_access` ;

-- -----------------------------------------------------
-- Schema control_access
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `control_access` DEFAULT CHARACTER SET utf8 ;
USE `control_access` ;

-- -----------------------------------------------------
-- Table `control_access`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_access`.`users` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `control_access`.`users` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `control_access`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_access`.`groups` (
  `id` INT UNSIGNED NULL AUTO_INCREMENT,
  `name_gropus` VARCHAR(45) NULL,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `control_access`.`groups` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `name_gropus_UNIQUE` ON `control_access`.`groups` (`name_gropus` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `control_access`.`user_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `control_access`.`user_groups` (
  `id` INT UNSIGNED NULL,
  `users_id` INT UNSIGNED NOT NULL,
  `groups_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  CONSTRAINT `fk_user_groups_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `control_access`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_groups_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `control_access`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `control_access`.`user_groups` (`id` ASC) VISIBLE;

CREATE INDEX `fk_user_groups_users_idx` ON `control_access`.`user_groups` (`users_id` ASC) VISIBLE;

CREATE INDEX `fk_user_groups_groups1_idx` ON `control_access`.`user_groups` (`groups_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
