-- MySQL Script generated by MySQL Workbench
-- Optimized and corrected version

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema control_access
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `control_access`;
CREATE SCHEMA IF NOT EXISTS `control_access` DEFAULT CHARACTER SET utf8;
USE `control_access`;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(45) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL -- Se amplió para permitir almacenamiento de hashes
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groups` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name_groups` VARCHAR(45) NOT NULL UNIQUE, -- Se corrigió el nombre de la columna
  `description` VARCHAR(200) NULL
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `user_groups` (Many-to-Many Relationship)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_groups` (
  `users_id` INT UNSIGNED NOT NULL,
  `groups_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`users_id`, `groups_id`), -- Se eliminó `id`, y se corrigió la clave primaria
  CONSTRAINT `fk_user_groups_users`
    FOREIGN KEY (`users_id`) REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_groups_groups`
    FOREIGN KEY (`groups_id`) REFERENCES `groups` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Restauración de configuraciones previas
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
